const userData = {
  githubUsername: "TeodoroTopa",
  name: "Teodoro Topa",
  designation: "Data Scientist",
  avatarUrl: "/avatar.png",
  email: "teodorotopa@gmail.com",
  phone: "+1 (202)-413-4213",
  address: "Chicago, IL, USA",
  projects: [
    {
      title: "Loisaba EarthRanger & Tableau Mapping Project",
      link: "https://github.com/TeodoroTopa/earthranger_tableau_integration_maps",
      imgUrl: "/leopard_leaving_tree.jpg",
    },
    {
      title: "Yelp Review Classification NLP Project",
      link: "https://github.com/TeodoroTopa/yelp_review_classification",
      imgUrl: "/confusion_matrix.png",
    },
    {
      title: "Cornell Course Recommendation Website",
      link: "https://github.com/TeodoroTopa/course_recommender_site",
      imgUrl: "/ccr.png",
    },
    {
      title: "Global Immigration Flow Visualization",
      link: "https://github.com/TeodoroTopa/global_immigrant_flow_viz",
      imgUrl: "/giflow.png",
    },
    {
      title: "Personal Website",
      link: "https://github.com/TeodoroTopa/teodorotopa_personal_website",
      imgUrl: "/pweb.png",
    },
    {
      title: "Chicago Housing MiniProject",
      link: "https://github.com/TeodoroTopa/chicago_housing_miniproject",
      imgUrl: "https://user-images.githubusercontent.com/27015256/265310506-aed5001c-ad2a-4a39-9d1c-b0d208aebdd0.png",
    },
    {
      title: "Kenyan Bird Quiz",
      link: "https://github.com/TeodoroTopa/birdquiz",
      imgUrl: "https://user-images.githubusercontent.com/27015256/265303839-34791da9-3db2-4836-b0c4-090de2993c76.png",
    },
  ],
  about: {
    title:
      "I'm a data scientist with a strong interest in conservation and sustainability.",
    description: [
      'I grew up in Washington, DC before attending Cornell University and studying Environmental and Sustainability Sciences, as well as Information Science.',
      'At Cornell, I completed concentrations in Data Science, and Environmental Biology and Applied Ecology. Some of my favorite coursework included classes teaching information retrieval and Natural Language Processing (NLP), as well as Geographic Information Systems (GIS) and population biology.',
      'My ideal career would be to work at the intersection of wildlife conservation/sustainability and data science. Check out my experiences page to learn how I\'ve worked towards that so far!',
      'Currently, I live in Chicago and work at 84.51, a retail data science, insights, and media company, developing and executing data science solutions for Consumer Packaged Good (CPG) clients.',
      'Outside of work I enjoy playing soccer, singing (I did acappella at Cornell!), skiing, and traveling.',
      'Languages: English (fluent), Italian (fluent), Spanish (professional proficiency), French (Intermediate)',
      '\nOther stuff that didnt fit in the short bio:',
      'After graduating high school in 2017, I took a gap year and did three things:',
      '\t 1. Earned an apprentice safari guiding certification (FGASA Level 1) in South Africa. I lived on game reserves and was taught and assessed by Ecotraining, a guide training organization.',
      '\t 2. Taught skiing in Verbier, Switzerland after completing a BASI level 2 ski instructing certification.',
      '\t 3. Interned on Capitol Hill for Rep. Jerrold Nadler.',
      'I have Celiac and can\'t eat gluten (ask me for gluten free eats recs in DC, NYC, Ithaca, and Chicago!).',
      'My dad is Italian and I grew up speaking Italian at home. I want to live in Italy at some point!\n\n',
    ],
    currentProject: "the 84.51 Data Science team!",
    currentProjectUrl: "https://www.8451.com/solutions/research-analytics",
  },
  experience: [
    {
      title: "Data Scientist",
      company: "84.51",
      year: "2023",
      companyLink: "https://www.8451.com/",
      desc: "Data Scientist on the Commercial Insights and Loyalty, Partnerships & Delivery Team. \n\n Work with a small team to develop and execute data science solutions relating to purchasing patterns across the Kroger business. Primarily leverage Databricks, Pyspark, PowerBI and VSCode.",
    },
    {
      title: "Assistant to the Conservation Officer",
      company: "Loisaba Conservancy, Laikipia, Kenya",
      year: "2022",
      companyLink: "https://loisaba.com/",
      desc: "- Automated mapping and reporting of wildlife sightings by security team on daily patrols using EarthRanger and Tableau, saving multiple days of work in the creation of monthly reports. \n\n - Created a system for tracking touristic game drives in EarthRanger and Tableau, incorporating guests' wildlife sightings into the conservancy's tracking system while providing guests with interactive digital keepsakes.\n\n - Guided guests on safari game drives, leading educational tours in both English and Italian.",
    },
    {
      title: "Graduation",
      company: "Cornell University, Ithaca, NY.",
      year: "2022",
      companyLink: "https://cals.cornell.edu/",
      desc: "Graduated Magna Cum Laude with a double major in Environmental and Sustainability Sciences and Information Science.",
    },
    {
      title: "Project Manager and Consultant",
      company: "Social Business Consulting Cornell",
      year: "2019-22",
      companyLink: "https://www.sbccornell.org/",
      desc: "As Project Manager: Leader of a team of 6 consultants building a market entry plan, educational partner shortlist, and revenue projections for an organization entering the online professional training space. \n\n As consultant: Member of consulting group for socially conscious firms worldwide. Advise on marketing, investment strategy, management optimization, and perform data analytics and data system creation and management. For example, performed data analysis and assisted with data pipelining for human rights protection organization in Asia.",
    },
    {
      title: "Consulting Intern, Technology Segment",
      company: "FTI Consulting",
      year: "2021",
      companyLink: "https://www.fticonsulting.com/",
      desc: "Performed data intake, processing, quality assessment, and presentation tasks on external, client-facing eDiscovery engagements. Leveraged Relativity, Excel and PowerPoint to accomplish tasks. Managed internal training projects.",
    },
    {
      title: "Machine Learning Intern",
      company: "IvyOnline Academy",
      year: "2020",
      companyLink: "https://www.linkedin.com/company/ivyonline-academy/about/",
      desc: "Researching and assisting with the development of Machine Learning models in Python related to stock market predictions.",
    },  
    {
      title: "Data Science Intern",
      company: "Patriot Family Homes",
      year: "2020",
      companyLink: "https://www.patriotfamilyhomes.com/team",
      desc: "Performed data analysis and administration. Created MySQL database and migrated company data from excel to MySQL. Examined customer messages and leveraged Tableau visualizations to identify when customer service support must be most active.",
    },
    {
      title: "Data and Programming Intern",
      company: "RealtySage",
      year: "2020",
      companyLink: "https://www.realtysage.com/",
      desc: "Performed data aggregation and analysis, and completed programming tasks related to the creation of a home-ownership cost calculator for a sustainable real-estate listing service. Performed other related data tasks as needed.",
    },
    {
      title: "Policy Analyst, Environment and Technology",
      company: "Cornell Roosevelt Institute",
      year: "2019",
      companyLink: "https://cornellrooseveltinstitute.weebly.com/",
      desc: "Member of think tank that publishes opinion pieces and policy proposals. Most recently, authored op-ed on STEM education: https://www.cornellrooseveltinstitute.org/env/is-cornell-drowning-its-engineers-in-stem-",
    },
    {
      title: "Biodiversity Field Assistant",
      company: "Universidad San Francisco de Quito",
      year: "2019",
      companyLink: "https://www.usfq.edu.ec/es/opi/internacional",
      desc: "Worked in Spanish on a two-person team. Captured terrestrial birds of the Galapagos and took blood samples and body measurements. Compiled data for Universidad San Francisco de Quito’s Zoology Department study.",
    },
    {
      title: "Congressional Intern",
      company: "Office of Congressman Jerrold Nadler",
      year: "2018",
      companyLink: "https://nadler.house.gov/",
      desc: "Wrote memoranda on bills & constituent correspondence, answered the office telephone, welcomed visitors.",
    },
    {
      title: "Ski Instructor",
      company: "Adrenaline International Ski & Snowboard School in Verbier, Switzerland",
      year: "2018",
      companyLink: "https://adrenaline-verbier.ch/en/",
      desc: "Taught groups and individuals of all ages in English, French, Italian, and Spanish.",
    },
    {
      title: "Field Guide Trainee",
      company: "EcoTraining Field Guide and Nature Training",
      year: "2017",
      companyLink: "https://www.ecotraining.co.za/",
      desc: "Completed big game field guide training while living and camping in Kapama Private Game Reserve (PGR), Pridelands Conservancy, & Selati PGR. Studied for and passed exams on lowveld ecology and geology, animal behavior, bird sight and song recognition, hospitality, off-road driving, group safety and leadership, among others.",
    },
    {
      title: "High School",
      company: "Woodrow Wilson (renamed Jackson Reed) High School, Washington, DC.",
      year: "2017",
      companyLink: "https://jacksonreedhs.org/",
      desc: "Graduated 3rd in a class of 400. Played Varsity Soccer, and was very involved in the musical theater and Shakespeare theater programs.",
    },
  ],
  resumeUrl:
    "https://drive.google.com/file/d/1lFUaHkq22CRKgJph9w14G8gC0YfxVYh-/view?usp=sharing",
  socialLinks: {
    instagram: "https://www.instagram.com/uguay/",
    linkedin: "https://www.linkedin.com/in/teodoro-topa/",
    github: "https://github.com/TeodoroTopa",
    facebook: "https://www.facebook.com/teo.topa.7",
  },
};

export default userData;
